source ${genode_dir}/repos/world/run/qt5_webengine.inc

import_from_depot [depot_user]/src/falkon \
                  [depot_user]/src/nss3 \
                  [depot_user]/src/openssl \
                  [depot_user]/src/qt5_base \
                  [depot_user]/src/qt5_component \
                  [depot_user]/src/qt5_declarative \
                  [depot_user]/src/qt5_svg \
                  [depot_user]/src/qt5_webengine \
                  [depot_user]/src/qt5_webchannel \
                  [depot_user]/src/vfs_capture \
                  [depot_user]/src/vfs_jitterentropy \
                  [depot_user]/src/vfs_lwip \
                  [depot_user]/src/vfs_oss \
                  [depot_user]/src/vfs_qtwebengine_shm \
                  [depot_user]/src/vfs_xoroshiro

#
# Generate config
#

append config {
<config prio_levels="4">
	<parent-provides>}
append config [qt5_parent_provides]
append config {
	</parent-provides>
	<default caps="100"/>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>}

append config [qt5_start_nodes]

append config {

<!--
	<start name="vfs" caps="250">
		<resource name="RAM" quantum="256M"/>
		<provides> <service name="File_system"/> </provides>
		<config>
			<vfs>
				<jitterentropy name="random"/>
				<jitterentropy name="urandom"/>
			</vfs>
			<default-policy writeable="no" root="/"/>
		</config>
	</start>
-->

	<start name="falkon" caps="10000" priority="-1">
		<resource name="RAM" quantum="2G"/>
		<config ld_verbose="yes">
			<vfs>
				<dir name="dev">
					<dir name="pipe"> <pipe/> </dir>
					<log/>
					<jitterentropy name="entropy"/>
					<xoroshiro name="random" seed_path="/dev/entropy"/>
					<xoroshiro name="urandom" seed_path="/dev/entropy"/>
					<!--<fs/>-->
					<inline name="rtc">2025-12-05 00:01</inline>
					<oss name="dsp"/>
					<capture/>
				</dir>
				<dir name="shm"> <qtwebengine_shm/> </dir>
				<dir name="socket">
					<lwip dhcp="yes"/>
					<!--<fs/>-->
				</dir>
				<dir name=".config"> <ram/> </dir>
				<dir name="tmp"> <ram/> </dir>
				<dir name="downloads"> <ram/> </dir>
				<tar name="qt5_dejavusans.tar"/>
				<tar name="qt5_declarative_qml.tar"/>
				<tar name="qt5_libqgenode.tar"/>
				<tar name="qt5_libqsqlite.tar"/>
				<tar name="qt5_libqsvg.tar"/>
				<tar name="qt5_webengine_qml.tar"/>
				<tar name="qt5_webengine_resources.tar"/>
				<tar name="qt5_webengine_translations.tar"/>
				<tar name="falkon_theme.tar"/>
				<ram/>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" pipe="/dev/pipe" rng="/dev/random" rtc="/dev/rtc" socket="/socket" pid="1">
				<mmap align_log2="21"/>
				<pthread placement="single-cpu"/>
			</libc>
			<arg value="falkon"/>
			<arg value="--webEngineArgs"/>
			<arg value="--single-process"/>
			<arg value="--no-sandbox"/>
			<arg value="--disable-gpu-compositing"/>
			<arg value="--enable-logging"/>
			<arg value="--log-level=3"/>
			<arg value="--v=0"/>
			<arg value="http://genodians.org"/>
			<env key="QT_QUICK_BACKEND" value="software"/>
		</config>
		<route>
			<service name="Gui"> <child name="wm"/> </service>
			<service name="Play"> <child name="drivers"/> </service>
			<service name="Record"> <child name="drivers"/> </service>
			<service name="Capture"> <child name="black_hole"/> </service>
			<service name="Nic"> <child name="nic_router"/> </service>
			<service name="Report" label="shape">
				<child name="pointer" label="wm -> falkon -> shape"/>
			</service>
			<service name="ROM" label="mesa_gpu.lib.so"> <parent label="mesa_gpu-softpipe.lib.so" /> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>
</config>}

install_config $config

#
# Boot modules
#

append boot_modules "[qt5_boot_modules] [build_artifacts]"

build_boot_image $boot_modules

append qemu_args "-m 4096"
append_qemu_nic_args

run_genode_until forever
