source ${genode_dir}/repos/world/run/qt5_webengine.inc

import_from_depot [depot_user]/src/qt5_component \
                  [depot_user]/src/vfs_jitterentropy \
                  [depot_user]/src/vfs_lwip \
                  [depot_user]/pkg/usb_webcam

#
# Build
#

append build_components {
	app/falkon
	lib/ld
	lib/freebl3
	lib/libcrypto
	lib/nss3
	lib/nssckbi
	lib/softokn3
	lib/vfs_capture
	lib/vfs_lwip
	lib/vfs_jitterentropy
	lib/vfs_libusb
	lib/vfs_oss
	lib/vfs_pipe
	lib/vfs_qtwebengine_shm
	server/jitter_sponge
	server/vfs
	app/top
	app/usb_webcam
}

build $build_components

#
# Generate config
#

append config {
<config prio_levels="4">
	<affinity-space width="2"/>
	<parent-provides>}
append config [qt5_parent_provides]
append config {
	</parent-provides>
	<default caps="100"/>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>}

append config [qt5_start_nodes]

append config {

<!--
	<start name="vfs" caps="250">
		<resource name="RAM" quantum="256M"/>
		<provides> <service name="File_system"/> </provides>
		<config>
			<vfs>
				<lwip dhcp="yes"/>
			</vfs>
			<default-policy writeable="yes" root="/"/>
		</config>
	</start>
-->


	<start name="jitter_sponge">
		<resource name="RAM" quantum="1M"/>
		<provides>
			<service name="Terminal"/>
		</provides>
	</start>


<!--
	<start name="top">
		<resource name="RAM" quantum="2M"/>
		<config period_ms="5000"/>
	</start>
-->

	<start name="falkon" caps="10000" priority="-1">
		<resource name="RAM" quantum="2G"/>
		<affinity xpos="1" width="1"/>
		<config ld_verbose="yes">
			<vfs>
				<dir name="dev">
					<dir name="pipe"> <pipe/> </dir>
					<log/>
<!--
						<jitterentropy name="random"/>
						<jitterentropy name="urandom"/>
-->

						<terminal name="random" raw="yes"/>
						<terminal name="urandom" raw="yes"/>

					<!--<fs/>-->
					<inline name="rtc">2024-05-10 00:01</inline> 
					<oss name="dsp"/>
					<capture/>
				</dir>
				<dir name="shm"> <qtwebengine_shm/> </dir>
				<dir name="socket">
					<lwip dhcp="yes"/>
					<!--<fs/>-->
				</dir>
				<dir name="tmp"> <ram/> </dir>
				<tar name="qt5_dejavusans.tar"/>
				<tar name="qt5_declarative_qml.tar"/>
				<tar name="qt5_libqgenode.tar"/>
				<tar name="qt5_libqsqlite.tar"/>
				<tar name="qt5_libqsvg.tar"/>
				<tar name="qt5_webengine_qml.tar"/>
				<tar name="qt5_webengine_resources.tar"/>
				<tar name="qt5_webengine_translations.tar"/>
				<tar name="falkon_theme.tar"/>
				<ram/>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" pipe="/dev/pipe" rng="/dev/random" rtc="/dev/rtc" socket="/socket" pid="1">
				<mmap align_log2="21"/>
				<pthread placement="single-cpu"/>
			</libc>
			<arg value="falkon"/>
			<arg value="--single-process"/>
			<arg value="--no-sandbox"/>
			<arg value="--disable-gpu-compositing"/>
			<arg value="--enable-logging"/>
			<arg value="--log-level=3"/>
			<arg value="--v=0"/>
			<arg value="--use-fake-device-for-media-stream"/>
			<env key="QT_QUICK_BACKEND" value="software"/>
		</config>
		<route>
			<service name="Gui"> <child name="wm"/> </service>
			<service name="Audio_out"> <child name="drivers"/> </service>
			<service name="Audio_in"> <child name="drivers"/> </service>
			<service name="Capture"> <child name="webcam"/> </service>
			<service name="Nic"> <child name="nic_router"/> </service>
			<service name="Report" label="shape">
				<child name="pointer" label="wm -> falkon -> shape"/>
			</service>
			<service name="ROM" label="mesa_gpu_drv.lib.so"> <parent label="mesa_gpu-softpipe.lib.so" /> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>
</config>}

install_config $config

#
# Boot modules
#

append boot_modules "[qt5_boot_modules] [build_artifacts]"

build_boot_image $boot_modules

proc qemu_nic_model {} {
	if [have_spec x86]         { return e1000 }
	if [have_spec lan9118]     { return lan9118 }
	if [have_spec cadence_gem] { return cadence_gem }
	return nic_model_missing
}

append qemu_args " -netdev user,id=net0 "
append qemu_args " -net nic,model=[qemu_nic_model],netdev=net0 "

run_genode_until forever
