source ${genode_dir}/repos/world/run/qt5_webengine.inc


import_from_depot \
                  [depot_user]/src/qt5_component \
                  [depot_user]/src/qt5_graphicaleffects \
                  [depot_user]/src/ubuntu_ui_extras \
                  [depot_user]/src/vfs_jitterentropy \
                  [depot_user]/src/vfs_lxip \
                  [depot_user]/pkg/usb_webcam \
                  [depot_user]/raw/ubuntu_themes \
                  [depot_user]/src/dummy_rtc_drv \

#
# Build
#

append build_components {
	app/morph-browser
	lib/ld
	lib/freebl3
	lib/nssckbi
	lib/softokn3
	lib/vfs_capture
	lib/vfs_gpu
	lib/vfs_lxip
	lib/vfs_jitterentropy
	lib/vfs_libusb
	lib/vfs_oss
	lib/vfs_pipe
	lib/vfs_qtwebengine_shm
	server/jitter_sponge
	server/vfs
	app/top
	app/usb_webcam
	server/black_hole
	lib/qt5_quickcontrols2
	lib/ubuntu-ui-toolkit
	lib/ubuntu-ui-extras
}

build $build_components

#
# Generate config
#

append config {
<config prio_levels="4">
	<parent-provides>}
append config [qt5_parent_provides]
append config {
	</parent-provides>
	<default caps="100"/>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>}

append config [qt5_start_nodes]

append config {


	<start name="vfs" caps="250">
		<resource name="RAM" quantum="256M"/>
		<provides> <service name="File_system"/> </provides>
		<config>
			<vfs>
				<lxip dhcp="yes"/>
			</vfs>
			<default-policy writeable="yes" root="/"/>
		</config>
	</start>



	<start name="jitter_sponge">
		<resource name="RAM" quantum="1M"/>
		<provides>
			<service name="Terminal"/>
		</provides>
	</start>


<!--
	<start name="top">
		<resource name="RAM" quantum="2M"/>
		<config period_ms="2000"/>
	</start>
-->

	<start name="black_hole">
		<resource name="RAM" quantum="1M"/>
		<provides>
			<service name="Audio_out"/>
			<service name="Audio_in"/>
			<service name="Capture"/>
		</provides>
		<config>
			<audio_out/>
			<audio_in/>
			<capture/>
		</config>
	</start>

	<start name="dummy_rtc_drv">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Rtc"/> </provides>
	</start>

	<start name="morph-browser" caps="10000" priority="0">
		<resource name="RAM" quantum="2048M"/>
		<config ld_verbose="yes">
			<vfs>
				<dir name="dev">
					<dir name="pipe"> <pipe/> </dir>
					<log/>
<!--
						<jitterentropy name="random"/>
						<jitterentropy name="urandom"/>
-->

						<terminal name="random" raw="yes"/>
						<terminal name="urandom" raw="yes"/>

					<!--<fs/>-->
					<inline name="rtc">2023-12-19 00:01</inline> 
					<oss name="dsp"/>
					<capture width="640" height="480"/>
					<null/>
				</dir>
				<dir name="shm"> <qtwebengine_shm/> </dir>
				<dir name="socket">
					<!--<lxip dhcp="yes"/>-->
					<fs/>
				</dir>
				<dir name="tmp"> <ram/> </dir>
				<tar name="qt5_dejavusans.tar"/>
				<tar name="qt5_declarative_qml.tar"/>
				<tar name="qt5_libqgenode.tar"/>
				<tar name="qt5_libqsqlite.tar"/>
				<tar name="qt5_libqsvg.tar"/>
				<tar name="qt5_graphicaleffects_qml.tar"/>
				<tar name="qt5_quickcontrols2_qml.tar"/>
				<tar name="qt5_webengine_qml.tar"/>
				<tar name="qt5_webengine_resources.tar"/>
				<tar name="qt5_webengine_translations.tar"/>
				<tar name="ubuntu-ui-toolkit_qml.tar"/>
				<tar name="ubuntu-ui-extras_qml.tar"/>
				<tar name="morph-browser_qml.tar"/>
				<tar name="ubuntu-themes.tar"/>
				<ram/>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" pipe="/dev/pipe" rtc="/dev/rtc" socket="/socket" pid="1">
				<mmap align_log2="21"/>
				<!--<pthread placement="single-cpu"/>-->
			</libc>
			<arg value="morph-browser"/>
			<arg value="--single-process"/>
			<arg value="--no-sandbox"/>
			<arg value="--disable-gpu-compositing"/>
			<arg value="--disable-logging"/>
			<arg value="--log-level=3"/>
			<arg value="--v=0"/>
			<arg value="--force-webrtc-ip-handling-policy=default_public_interface_only"/>
			<arg value="- -use-fake-device-for-media-stream"/>
			<env key="QT_QUICK_BACKEND" value="software"/>
			<env key="GRID_UNIT_PX" value="8"/>
			<env key="QT_FONT_DPI" value="271"/>
			<env key="QT_ENABLE_HIGHDPI_SCALING" value="0"/>
			<!--<env key="QT_LOGGING_RULES" value="qml.debug=false"/>-->
			<!--<env key="QT_SCALE_FACTOR" value="2"/>-->
			<!--<env key="QT_LOGGING_RULES" value="qt.scenegraph.renderloop=true;qt.scenegraph.time.texture=true;qt.scenegraph.time.renderer=true"/>-->
			<!--<env key="QT_LOGGING_RULES" value="qt.scenegraph.time.renderloop=true"/>-->
		</config>
		<route>
			<service name="Gui"> <child name="wm"/> </service>
			<service name="Audio_out"> <child name="black_hole"/> </service>
			<service name="Audio_in"> <child name="black_hole"/> </service>
			<service name="Capture"> <child name="black_hole"/> </service>
			<service name="Nic"> <child name="nic_router"/> </service>
			<service name="Report" label="shape">
				<child name="pointer" label="wm -> morph-browser -> shape"/>
			</service>
			<service name="ROM" label="mesa_gpu_drv.lib.so"> <parent label="mesa_gpu-softpipe.lib.so" /> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>
</config>}

install_config $config

#
# Boot modules
#

append boot_modules [qt5_boot_modules]

append boot_modules {
	freebl3.lib.so
	jitter_sponge
	libQt5Core.lib.so
	libQt5Gui.lib.so
	libQt5Network.lib.so
	libQt5Qml.lib.so
	libQt5QmlModels.lib.so
	libQt5QmlWorkerScript.lib.so
	libQt5Quick.lib.so
	libQt5QuickControls2.lib.so
	libQt5QuickTemplates2.lib.so
	libQt5Sql.lib.so
	libQt5Svg.lib.so
	libQt5Test.lib.so
	libQt5WebChannel.lib.so
	libQt5WebEngine.lib.so
	libQt5WebEngineCore.lib.so
	libQt5Widgets.lib.so
	libQt5Xml.lib.so
	libUbuntuComponents.lib.so
	libUbuntuComponentsStyles.lib.so
	libUbuntuGestures.lib.so
	libUbuntuMetrics.lib.so
	libUbuntuToolkit.lib.so
	libdrm.lib.so
	libmodelsplugin.lib.so
	libmorph-web-plugin.lib.so
	libqgenode.lib.so
	libqmlfolderlistmodelplugin.lib.so
	libqmlplugin.lib.so
	libqmlsettingsplugin.lib.so
	libqsqlite.lib.so
	libqsvg.lib.so
	libqtquick2plugin.lib.so
	libqtquickcontrols2plugin.lib.so
	libqtquicktemplates2plugin.lib.so
	libqtwebengineplugin.lib.so
	libwindowplugin.lib.so
	morph-browser
	morph-browser_qml.tar
	nss3.lib.so
	nssckbi.lib.so
	qt5_declarative_qml.tar
	qt5_libqgenode.tar
	qt5_libqsqlite.tar
	qt5_libqsvg.tar
	qt5_quickcontrols2_qml.tar
	qt5_webengine_qml.tar
	qt5_webengine_resources.tar
	qt5_webengine_translations.tar
	softokn3.lib.so
	ubuntu-ui-toolkit_qml.tar
	vfs_capture.lib.so
	vfs_gpu.lib.so
	vfs_oss.lib.so
	vfs_qtwebengine_shm.lib.so
}

append boot_modules {
	egl.lib.so
	expat.lib.so
	glapi.lib.so
	ld.lib.so
	libQt5QuickWidgets.lib.so
	libQt5WebEngineWidgets.lib.so
	libc.lib.so
	libm.lib.so
	libqjpeg.lib.so
	libqquicklayoutsplugin.lib.so
	libubuntu-ui-extras-plugin.lib.so
	libusb.lib.so
	mesa.lib.so
	qt5_component.lib.so
	stdcxx.lib.so
	top
	ubuntu-ui-extras_qml.tar
	vfs
	vfs.lib.so
	vfs_jitterentropy.lib.so
	vfs_libusb.lib.so
	lxip.lib.so
	vfs_lxip.lib.so
	vfs_pipe.lib.so
	fs
	black_hole
}

build_boot_image $boot_modules


proc qemu_nic_model {} {
	if [have_spec x86]         { return e1000 }
	if [have_spec lan9118]     { return lan9118 }
	if [have_spec cadence_gem] { return cadence_gem }
	return nic_model_missing
}

append qemu_args " -netdev user,id=net0 "
append qemu_args " -net nic,model=[qemu_nic_model],netdev=net0 "

run_genode_until forever
