source ${genode_dir}/repos/libports/run/qt5_common.inc

import_from_depot [depot_user]/src/qt5_component \
                  [depot_user]/src/qt5_declarative \
                  [depot_user]/src/qt5_graphicaleffects \
                  [depot_user]/src/qt5_svg \
                  [depot_user]/src/ubuntu_ui_toolkit \
                  [depot_user]/src/ubuntu_ui_toolkit_launcher \
                  [depot_user]/raw/ubuntu_ui_toolkit_gallery \
                  [depot_user]/raw/ubuntu_themes \
                  [depot_user]/src/top

build {
	drivers/gpu/lima
	lib/mesa/lima
	lib/vfs/gpu
}

#
# Generate config
#

append config {
<config>
	<affinity-space width="4"/>
	<parent-provides>}
append config [qt5_parent_provides]
append config {
	</parent-provides>
	<default caps="100"/>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>}

append config [qt5_start_nodes]

append config {
<!--
	<start name="top">
		<resource name="RAM" quantum="2M"/>
		<config period_ms="10000"/>
	</start>
-->
	<start name="gpu_drv" caps="5000">
		<binary name="lima_gpu_drv"/>
		<provides> <service name="Gpu"/> </provides>
		<resource name="RAM" quantum="240M"/>
		<affinity xpos="3" width="1"/>
		<route>
			<service name="ROM" label_last="dtb">
				<parent label="lima-pinephone.dtb"/>
			</service>
			<service name="Platform"> <child name="drivers"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="ubuntu-ui-toolkit-launcher" caps="1000">
		<resource name="RAM" quantum="200M"/>
		<affinity xpos="0" width="3"/>
		<config ld_verbose="yes">
			<vfs>
				<dir name="dev">
					<gpu/>
					<log/>
					<inline name="rtc">2018-01-01 00:01</inline>
				</dir>
				<dir name="pipe"> <pipe/> </dir>
				<tar name="qt5_declarative_qml.tar"/>
				<tar name="qt5_dejavusans.tar"/>
				<tar name="qt5_graphicaleffects_qml.tar"/>
				<tar name="qt5_libqgenode.tar"/>
				<tar name="qt5_libqjpeg.tar"/>
				<tar name="qt5_libqsvg.tar"/>
				<tar name="ubuntu-ui-toolkit_qml.tar"/>
				<tar name="ubuntu_ui_toolkit_gallery.tar"/>
				<tar name="ubuntu-themes.tar"/>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" pipe="/pipe" rtc="/dev/rtc"/>
			<arg value="ubuntu-ui-toolkit-launcher"/>
			<arg value="/ubuntu-ui-toolkit-gallery/ubuntu-ui-toolkit-gallery.qml"/>
			<env key="QT_SCALE_FACTOR" value="2"/>
		</config>
		<route>
			<service name="Gui"> <child name="nitpicker"/> </service>
			<service name="Gpu"> <child name="gpu_drv"/> </service>
			<service name="Report" label="shape">
				<child name="pointer" label="wm -> ubuntu-ui-toolkit-launcher -> shape"/>
			</service>
			<service name="ROM" label="libdrm.lib.so">
				<parent label="libdrm.lib.so"/>
			</service>
			<service name="ROM" label="mesa_gpu_drv.lib.so">
				<parent label="mesa_gpu-lima.lib.so" />
			</service>
			<service name="ROM" label="mesa.lib.so">
				<parent label="mesa.lib.so"/>
			</service>
			<any-service> <parent /> <any-child/> </any-service>
		</route>
	</start>
</config>
}

install_config $config

#
# Boot modules
#

append boot_modules [qt5_boot_modules]

append boot_modules {
	egl.lib.so
	glapi.lib.so
	lima_gpu_drv
	lima-pinephone.dtb
	mesa.lib.so
	mesa_gpu-lima.lib.so
	vfs_gpu.lib.so
}

build_boot_image $boot_modules

run_genode_until forever
