source ${genode_dir}/repos/libports/run/qt5_common.inc

import_from_depot [depot_user]/src/qt5_component \
                  [depot_user]/src/qt5_declarative \
                  [depot_user]/src/qt5_svg

build { test/ubuntu-ui-toolkit-launcher }

#
# Generate config
#

append config {
<config>
	<parent-provides>}
append config [qt5_parent_provides]
append config {
	</parent-provides>
	<default caps="100"/>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>}

append config [qt5_start_nodes]

append config {
	<start name="ubuntu-ui-toolkit-launcher" caps="500">
		<resource name="RAM" quantum="100M"/>
		<config ld_verbose="yes">
			<vfs>
				<dir name="dev">
					<log/>
					<inline name="rtc">2018-01-01 00:01</inline>
				</dir>
				<dir name="pipe"> <pipe/> </dir>
				<tar name="qt5_declarative_qml.tar"/>
				<tar name="qt5_dejavusans.tar"/>
				<tar name="qt5_libqgenode.tar"/>
				<tar name="qt5_libqjpeg.tar"/>
				<tar name="qt5_libqsvg.tar"/>
				<tar name="ubuntu-ui-toolkit_qml.tar"/>
				<tar name="ubuntu-ui-toolkit-unit-converter.tar"/>
				<tar name="suru_icons.tar"/>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" pipe="/pipe" rtc="/dev/rtc"/>
			<arg value="ubuntu-ui-toolkit-launcher"/>
			<arg value="/unit-converter/unit-converter.qml"/>
		</config>
		<route>
			<service name="Gui"> <child name="wm"/> </service>
			<service name="Report" label="shape">
				<child name="pointer" label="wm -> ubuntu-ui-toolkit-launcher -> shape"/>
			</service>
			<service name="ROM" label="mesa_gpu_drv.lib.so">
				<parent label="mesa_gpu-softpipe.lib.so" />
			</service>
			<any-service> <parent /> <any-child/> </any-service>
		</route>
	</start>
</config>
}

install_config $config

#
# Boot modules
#

append boot_modules [qt5_boot_modules]
append boot_modules {
	ubuntu-ui-toolkit-launcher
	libUbuntuComponents.lib.so
	libUbuntuComponentsStyles.lib.so
	libUbuntuGestures.lib.so
	libUbuntuMetrics.lib.so
	libUbuntuPerformanceMetrics.lib.so
	libUbuntuToolkit.lib.so
	ubuntu-ui-toolkit_qml.tar
	ubuntu-ui-toolkit-unit-converter.tar
	libQt5Core.lib.so
	libQt5Gui.lib.so
	libQt5Qml.lib.so
	libQt5Quick.lib.so
	libc.lib.so
	ld.lib.so
	mesa.lib.so
	suru_icons.tar
}

build_boot_image $boot_modules

run_genode_until forever
